networks: 
  - name: hj-test1
    vlanId: 671
  - name: hj-test2
    vlanId: 672

# networks
#   name: hj-test1
#   vlanId: 329

serverTemplates:
  - name: hj-sptemplate1
    enclosureGroup: DCA-SolCenter-EG
    serverHardwareType: SY 480 Gen9 3
    